config/routes.rb
Corruptos::Application.routes.draw do
  get "relatorios/index"
  match 'relatorios/candidato', to: 'relatorios#candidato'
  match 'relatorios/zona', to: 'relatorios#zona'
  match 'relatorios/secao', to: 'relatorios#secao'
  match 'relatorios/municipio', to: 'relatorios#municipio'
  match 'relatorios' => 'relatorios#index'

  resources :votos_urnas

  resources :candidaturas

  resources :coligacao_partidos

  resources :coligacaos

  resources :cargo_eleicaos

  resources :partidos
  match 'partidos/busca_partidos/', to: 'partidos#busca_partidos'

  resources :partidos do
    collection { post :search, to: 'partidos#index' }
  end

  resources :candidatos
  match 'candidatos/carrega_dados/:cpf', to: 'candidatos#carrega_dados'

  resources :cargos

  resources :eleicaos

  resources :secaos

  resources :zonas
  match 'zonas/busca_secoes/:id', to: 'zonas#busca_secoes'

  resources :titulos

  resources :eleitors

  resources :enderecos
  match 'enderecos/busca_cep/:cep', to: 'enderecos#busca_cep'

  resources :municipios
  match 'municipios/busca_zonas/:municipio', to: 'municipios#busca_zonas'

  resources :ufs
  match 'ufs/busca_municipios/:uf', to: 'ufs#busca_municipios'

  authenticated :user do
    root to: 'home#index'
  end
  root to: "home#index"
  devise_for :users
  resources :users
end

app/models/cargo.rb
class Cargo < ActiveRecord::Base
  attr_accessible :nome
  has_many :cargo_eleicaos
  has_many :eleicaos, :through => :cargo_eleicaos

  validates :nome, :presence => true, :uniqueness => true
end

app/controllers/cargos_controller.rb
class CargosController < ApplicationController
  # GET /cargos
  # GET /cargos.json
  def index
    @cargos = Cargo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cargos }
    end
  end

  # GET /cargos/1
  # GET /cargos/1.json
  def show
    @cargo = Cargo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cargo }
    end
  end

  # GET /cargos/new
  # GET /cargos/new.json
  def new
    @cargo = Cargo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cargo }
    end
  end

  # GET /cargos/1/edit
  def edit
    @cargo = Cargo.find(params[:id])
  end

  # POST /cargos
  # POST /cargos.json
  def create
    @cargo = Cargo.new(params[:cargo])

    respond_to do |format|
      if @cargo.save
        format.html { redirect_to @cargo, notice: 'Cargo was successfully created.' }
        format.json { render json: @cargo, status: :created, location: @cargo }
      else
        format.html { render action: "new" }
        format.json { render json: @cargo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cargos/1
  # PUT /cargos/1.json
  def update
    @cargo = Cargo.find(params[:id])

    respond_to do |format|
      if @cargo.update_attributes(params[:cargo])
        format.html { redirect_to @cargo, notice: 'Cargo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cargo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cargos/1
  # DELETE /cargos/1.json
  def destroy
    @cargo = Cargo.find(params[:id])
    @cargo.destroy

    respond_to do |format|
      format.html { redirect_to cargos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/cargos_helper.rb
module CargosHelper
end

app/views/cargos/_form.html.erb
<%= simple_form_for(@cargo) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nome %>
  </div>

  <div class="form-inputs">
    <%= f.button :submit, "Salvar" %>
  </div>
<% end %>

app/views/cargos/edit.html.erb
<div class="page-header"><h1> cargo</h1></div>

<%= render 'form' %>

<%= link_to content_tag(:span, "Exibir"), @cargo %> |
<%= link_to content_tag(:span, "Voltar"), cargos_path %>

app/views/cargos/index.html.erb
<div class="page-header"><h1>Cargos</h1></div>

<table class="table table-condensed table-striped">
  <tr>
    <th>Nome</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cargos.each do |cargo| %>
  <tr>
    <td><%= cargo.nome %></td>
    <td><%= link_to content_tag(:span, "Exibir"), cargo, :class => "btn btn-small" %></td>
    <td><%= link_to content_tag(:span, "Alterar"), edit_cargo_path(cargo), :class => "btn btn-small" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Novo Cargo', new_cargo_path, :class => "btn btn-small btn-info" %>

app/views/cargos/new.html.erb
<div class="page-header"><h1>Nova cargo</h1></div>

<%= render 'form' %>

<%= link_to content_tag(:span, "Voltar"), cargos_path %>

app/views/cargos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @cargo.nome %>
</p>


<%= link_to content_tag(:span, "Alterar"), edit_cargo_path(@cargo) %> |
<%= link_to content_tag(:span, "Voltar"), cargos_path %>