config/routes.rb
Corruptos::Application.routes.draw do
  get "relatorios/index"
  match 'relatorios/candidato', to: 'relatorios#candidato'
  match 'relatorios/zona', to: 'relatorios#zona'
  match 'relatorios/secao', to: 'relatorios#secao'
  match 'relatorios/municipio', to: 'relatorios#municipio'
  match 'relatorios' => 'relatorios#index'

  resources :votos_urnas

  resources :candidaturas

  resources :coligacao_partidos

  resources :coligacaos

  resources :cargo_eleicaos

  resources :partidos
  match 'partidos/busca_partidos/', to: 'partidos#busca_partidos'

  resources :partidos do
    collection { post :search, to: 'partidos#index' }
  end

  resources :candidatos
  match 'candidatos/carrega_dados/:cpf', to: 'candidatos#carrega_dados'

  resources :cargos

  resources :eleicaos

  resources :secaos

  resources :zonas
  match 'zonas/busca_secoes/:id', to: 'zonas#busca_secoes'

  resources :titulos

  resources :eleitors

  resources :enderecos
  match 'enderecos/busca_cep/:cep', to: 'enderecos#busca_cep'

  resources :municipios
  match 'municipios/busca_zonas/:municipio', to: 'municipios#busca_zonas'

  resources :ufs
  match 'ufs/busca_municipios/:uf', to: 'ufs#busca_municipios'

  authenticated :user do
    root to: 'home#index'
  end
  root to: "home#index"
  devise_for :users
  resources :users
end

app/models/cargo_eleicao.rb
class CargoEleicao < ActiveRecord::Base
  belongs_to :cargo
  belongs_to :eleicao
  has_one :coligacao
  has_many :candidaturas

  # Deve possuir uf ou município ou vazio (presidente)
  belongs_to :municipio
  belongs_to :uf

  attr_accessible :vagas, :cargo_id, :eleicao_id, :uf_id, :municipio_id

  validates_presence_of :cargo, :eleicao
end

app/controllers/cargo_eleicaos_controller.rb
class CargoEleicaosController < ApplicationController
  # GET /cargo_eleicaos
  # GET /cargo_eleicaos.json
  def index
    @cargo_eleicaos = CargoEleicao.paginate(:page => params[:page], :per_page => 30)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cargo_eleicaos }
    end
  end

  # GET /cargo_eleicaos/1
  # GET /cargo_eleicaos/1.json
  def show
    @cargo_eleicao = CargoEleicao.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cargo_eleicao }
    end
  end

  # GET /cargo_eleicaos/new
  # GET /cargo_eleicaos/new.json
  def new
    @uf = Uf.first
    @municipios = @uf.municipios
    @cargo_eleicao = Eleicao.find(:first, :conditions => "status = true").cargo_eleicaos

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cargo_eleicao }
    end
  end

  # GET /cargo_eleicaos/1/edit
  def edit
    @cargo_eleicao = CargoEleicao.find(params[:id])
  end

  # POST /cargo_eleicaos
  # POST /cargo_eleicaos.json
  def create
    @cargo_eleicao = CargoEleicao.new(params[:cargo_eleicao])

    respond_to do |format|
      if @cargo_eleicao.save
        format.html { redirect_to @cargo_eleicao, notice: 'Cargo eleicao was successfully created.' }
        format.json { render json: @cargo_eleicao, status: :created, location: @cargo_eleicao }
      else
        format.html { render action: "new" }
        format.json { render json: @cargo_eleicao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cargo_eleicaos/1
  # PUT /cargo_eleicaos/1.json
  def update
    @cargo_eleicao = CargoEleicao.find(params[:id])

    respond_to do |format|
      if @cargo_eleicao.update_attributes(params[:cargo_eleicao])
        format.html { redirect_to @cargo_eleicao, notice: 'Cargo eleicao was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cargo_eleicao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cargo_eleicaos/1
  # DELETE /cargo_eleicaos/1.json
  def destroy
    @cargo_eleicao = CargoEleicao.find(params[:id])
    @cargo_eleicao.destroy

    respond_to do |format|
      format.html { redirect_to cargo_eleicaos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/cargo_eleicaos_helper.rb
module CargoEleicaosHelper
end

app/views/cargo_eleicaos/_cargo_eleicao_fields.html.erb
<%= f.input :eleicao_id, as: :hidden, input_html: { value: eleicao_atual.id, class: "cargo_eleicao_select" } %>
<% if @coligacao.cargo_eleicao %>
	<%= f.input :cargo_id, include_blank: false, collection: eleicao_atual.cargos.uniq, label_method: lambda { |obj| obj.nome }, input_html: {onchange: "seleciona_cargo()"}, selected: @coligacao.cargo_eleicao.cargo_id %>
	<%= f.input :uf_id, include_blank: false, collection: Uf.all, label_method: lambda { |obj| obj.nome }, input_html: {onchange: "busca_municipios()", class: "uf_select" }, selected: @coligacao.cargo_eleicao.uf_id %>
	<% if @coligacao.cargo_eleicao.uf %>
		<%= f.input :municipio_id, include_blank: false, collection: @coligacao.cargo_eleicao.uf.municipios, label_method: lambda { |obj| obj.nome }, input_html: {onchange:"busca_partidos_disponiveis()", class: "municipio_select municipio_coligacao"}, selected: @coligacao.cargo_eleicao.municipio_id %>
	<% else %>
		<%= f.input :municipio_id, include_blank: false, collection: Uf.first.municipios, label_method: lambda { |obj| obj.nome }, input_html: {onchange:"busca_partidos_disponiveis()", class: "municipio_select municipio_coligacao", display: 'none'} %>
	<% end %>
<% else %>
	<%= f.input :cargo_id, include_blank: false, collection: eleicao_atual.cargos.uniq, label_method: lambda { |obj| obj.nome }, input_html: {onchange: "seleciona_cargo()"} %>
	<%= f.input :uf_id, include_blank: false, collection: Uf.all, label_method: lambda { |obj| obj.nome }, input_html: {onchange: "busca_municipios()", class: "uf_select" } %>
	<%= f.input :municipio_id, include_blank: false, collection: Uf.first.municipios, label_method: lambda { |obj| obj.nome }, input_html: {onchange:"busca_partidos_disponiveis()", class: "municipio_select municipio_coligacao"} %>
<% end %>

app/views/cargo_eleicaos/_form.html.erb
<%= simple_form_for(@cargo_eleicao) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :eleicao, :include_blank => false, :label_method => lambda { |ele| "#{ele.ano}" if ele.status == true } %>
    <%= f.association :cargo, :include_blank => false, :label_method => lambda { |car| "#{car.nome}" } %>
    <%= f.association :uf, :include_blank => false, :label_method => lambda { |uf| "#{uf.nome}" }, :input_html => { :rel => "/uf/municipios_do_estado", :class => "estado" } %>
    <%= f.association :municipio %>

    <%= f.input :vagas %>
  </div>

  <div class="form-inputs">
    <%= f.button :submit, "Salvar" %>
  </div>
<% end %>

app/views/cargo_eleicaos/edit.html.erb
<div class="page-header"><h1> cargo_eleicao</h1></div>

<%= render 'form' %>

<%= link_to content_tag(:span, "Exibir"), @cargo_eleicao %> |
<%= link_to content_tag(:span, "Voltar"), cargo_eleicaos_path %>

app/views/cargo_eleicaos/index.html.erb
<div class="page-header"><h1>Cargos por Eleição</h1></div>

<table class="table table-condensed table-striped">
  <tr>
    <th>Cargo</th>
    <th>Eleicao</th>
    <th>Uf</th>
    <th>Municipio</th>
    <th>Vagas</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cargo_eleicaos.each do |cargo_eleicao| %>
  <tr>
    <td><%= cargo_eleicao.cargo.nome %></td>
    <td><%= cargo_eleicao.eleicao.ano %></td>
    <td><%= cargo_eleicao.uf.sigla if cargo_eleicao.uf %></td>
    <td><%= cargo_eleicao.municipio.nome if cargo_eleicao.municipio%></td>
    <td><%= cargo_eleicao.vagas %></td>
    <td><%= link_to content_tag(:span, "Exibir"), cargo_eleicao, :class => "btn btn-small" %></td>
    <td><%= link_to content_tag(:span, "Alterar"), edit_cargo_eleicao_path(cargo_eleicao), :class => "btn btn-small" %></td>
  </tr>
<% end %>
</table>

<%= will_paginate @posts %>

<br />

<%= link_to 'Novo Cargo eleicao', new_cargo_eleicao_path %>

app/views/cargo_eleicaos/new.html.erb
<div class="page-header"><h1>Nova cargo_eleicao</h1></div>

<%= render 'form' %>

<%= link_to content_tag(:span, "Voltar"), cargo_eleicaos_path %>

app/views/cargo_eleicaos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cargo:</b>
  <%= @cargo_eleicao.cargo %>
</p>

<p>
  <b>Eleicao:</b>
  <%= @cargo_eleicao.eleicao %>
</p>

<p>
  <b>Municipio:</b>
  <%= @cargo_eleicao.municipio %>
</p>

<p>
  <b>Uf:</b>
  <%= @cargo_eleicao.uf %>
</p>

<p>
  <b>Vagas:</b>
  <%= @cargo_eleicao.vagas %>
</p>


<%= link_to content_tag(:span, "Alterar"), edit_cargo_eleicao_path(@cargo_eleicao) %> |
<%= link_to content_tag(:span, "Voltar"), cargo_eleicaos_path %>