config/routes.rb
Corruptos::Application.routes.draw do
  get "relatorios/index"
  match 'relatorios/candidato', to: 'relatorios#candidato'
  match 'relatorios/zona', to: 'relatorios#zona'
  match 'relatorios/secao', to: 'relatorios#secao'
  match 'relatorios/municipio', to: 'relatorios#municipio'
  match 'relatorios' => 'relatorios#index'

  resources :votos_urnas

  resources :candidaturas

  resources :coligacao_partidos

  resources :coligacaos

  resources :cargo_eleicaos

  resources :partidos
  match 'partidos/busca_partidos/', to: 'partidos#busca_partidos'

  resources :partidos do
    collection { post :search, to: 'partidos#index' }
  end

  resources :candidatos
  match 'candidatos/carrega_dados/:cpf', to: 'candidatos#carrega_dados'

  resources :cargos

  resources :eleicaos

  resources :secaos

  resources :zonas
  match 'zonas/busca_secoes/:id', to: 'zonas#busca_secoes'

  resources :titulos

  resources :eleitors

  resources :enderecos
  match 'enderecos/busca_cep/:cep', to: 'enderecos#busca_cep'

  resources :municipios
  match 'municipios/busca_zonas/:municipio', to: 'municipios#busca_zonas'

  resources :ufs
  match 'ufs/busca_municipios/:uf', to: 'ufs#busca_municipios'

  authenticated :user do
    root to: 'home#index'
  end
  root to: "home#index"
  devise_for :users
  resources :users
end

app/models/uf.rb
class Uf < ActiveRecord::Base
	has_many :municipios
	has_many :enderecos, :through => :municipios

	accepts_nested_attributes_for :municipios

  attr_accessible :nome, :sigla, :municipios

  validates_presence_of :nome, :sigla
end

app/controllers/ufs_controller.rb
class UfsController < ApplicationController

  def busca_municipios
    options = Uf.find(params[:uf]).municipios
    render :json => options
  end

  # GET /ufs
  # GET /ufs.json
  def index
    @q = Uf.search(params[:q])
    @ufs = @q.result(:distinct => true)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ufs }
    end
  end

  # GET /ufs/1
  # GET /ufs/1.json
  def show
    @uf = Uf.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @uf }
    end
  end

  # GET /ufs/new
  # GET /ufs/new.json
  def new
    @uf = Uf.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @uf }
    end
  end

  # GET /ufs/1/edit
  def edit
    @uf = Uf.find(params[:id])
  end

  # POST /ufs
  # POST /ufs.json
  def create
    @uf = Uf.new(params[:uf])

    respond_to do |format|
      if @uf.save
        format.html { redirect_to @uf, notice: 'Uf was successfully created.' }
        format.json { render json: @uf, status: :created, location: @uf }
      else
        format.html { render action: "new" }
        format.json { render json: @uf.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ufs/1
  # PUT /ufs/1.json
  def update
    @uf = Uf.find(params[:id])

    respond_to do |format|
      if @uf.update_attributes(params[:uf])
        format.html { redirect_to @uf, notice: 'Uf was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @uf.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ufs/1
  # DELETE /ufs/1.json
  def destroy
    @uf = Uf.find(params[:id])
    @uf.destroy

    respond_to do |format|
      format.html { redirect_to ufs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/ufs_helper.rb
module UfsHelper
end

app/views/ufs/_form.html.erb
<%= simple_form_for(@uf) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :sigla %>
    <%= f.input :nome %>
  </div>

  <div class="form-inputs">
    <%= f.button :submit, "Salvar" %>
  </div>
<% end %>

app/views/ufs/edit.html.erb
<div class="page-header"><h1> uf</h1></div>

<%= render 'form' %>

<%= link_to content_tag(:span, "Exibir"), @uf %> |
<%= link_to content_tag(:span, "Voltar"), ufs_path %>

app/views/ufs/index.html.erb
<div class="page-header"><h1>Estados</h1></div>

<table class="table table-condensed table-striped">
  <tr>
    <th><%= sort_link @q, :sigla, "Sigla" %></th>
    <th><%= sort_link @q, :nome, "Nome" %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ufs.each do |uf| %>
  <tr>
    <td><%= uf.sigla %></td>
    <td><%= uf.nome %></td>
    <td><%= link_to content_tag(:span, "Exibir"), uf, :class => "btn btn-small" %></td>
    <td><%= link_to content_tag(:span, "Alterar"), edit_uf_path(uf), :class => "btn btn-small" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nova UF', new_uf_path, :class => "btn btn-info btn-small"  %>

app/views/ufs/new.html.erb
<div class="page-header"><h1>Nova uf</h1></div>

<%= render 'form' %>

<%= link_to content_tag(:span, "Voltar"), ufs_path %>

app/views/ufs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Sigla:</b>
  <%= @uf.sigla %>
</p>

<p>
  <b>Nome:</b>
  <%= @uf.nome %>
</p>


<%= link_to content_tag(:span, "Alterar"), edit_uf_path(@uf) %> |
<%= link_to content_tag(:span, "Voltar"), ufs_path %>