config/routes.rb
Corruptos::Application.routes.draw do
  get "relatorios/index"
  match 'relatorios/candidato', to: 'relatorios#candidato'
  match 'relatorios/zona', to: 'relatorios#zona'
  match 'relatorios/secao', to: 'relatorios#secao'
  match 'relatorios/municipio', to: 'relatorios#municipio'
  match 'relatorios' => 'relatorios#index'

  resources :votos_urnas

  resources :candidaturas

  resources :coligacao_partidos

  resources :coligacaos

  resources :cargo_eleicaos

  resources :partidos
  match 'partidos/busca_partidos/', to: 'partidos#busca_partidos'

  resources :partidos do
    collection { post :search, to: 'partidos#index' }
  end

  resources :candidatos
  match 'candidatos/carrega_dados/:cpf', to: 'candidatos#carrega_dados'

  resources :cargos

  resources :eleicaos

  resources :secaos

  resources :zonas
  match 'zonas/busca_secoes/:id', to: 'zonas#busca_secoes'

  resources :titulos

  resources :eleitors

  resources :enderecos
  match 'enderecos/busca_cep/:cep', to: 'enderecos#busca_cep'

  resources :municipios
  match 'municipios/busca_zonas/:municipio', to: 'municipios#busca_zonas'

  resources :ufs
  match 'ufs/busca_municipios/:uf', to: 'ufs#busca_municipios'

  authenticated :user do
    root to: 'home#index'
  end
  root to: "home#index"
  devise_for :users
  resources :users
end

app/models/eleicao.rb
class Eleicao < ActiveRecord::Base
  attr_accessible :ano, :status, :cargos, :data

  has_many :cargo_eleicaos
  has_many :cargos, :through => :cargo_eleicaos

  validates_presence_of :ano
  validates_uniqueness_of :status, :if => :status
end

app/controllers/eleicaos_controller.rb
class EleicaosController < ApplicationController
  # GET /eleicaos
  # GET /eleicaos.json
  def index
    @eleicaos = Eleicao.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @eleicaos }
    end
  end

  # GET /eleicaos/1
  # GET /eleicaos/1.json
  def show
    @eleicao = Eleicao.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @eleicao }
    end
  end

  # GET /eleicaos/new
  # GET /eleicaos/new.json
  def new
    @eleicao = Eleicao.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @eleicao }
    end
  end

  # GET /eleicaos/1/edit
  def edit
    @eleicao = Eleicao.find(params[:id])
  end

  # POST /eleicaos
  # POST /eleicaos.json
  def create
    @eleicao = Eleicao.new(params[:eleicao])

    respond_to do |format|
      if @eleicao.save
        format.html { redirect_to @eleicao, notice: 'Eleicao was successfully created.' }
        format.json { render json: @eleicao, status: :created, location: @eleicao }
      else
        format.html { render action: "new" }
        format.json { render json: @eleicao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /eleicaos/1
  # PUT /eleicaos/1.json
  def update
    @eleicao = Eleicao.find(params[:id])

    respond_to do |format|
      if @eleicao.update_attributes(params[:eleicao])
        format.html { redirect_to @eleicao, notice: 'Eleicao was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @eleicao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eleicaos/1
  # DELETE /eleicaos/1.json
  def destroy
    @eleicao = Eleicao.find(params[:id])
    @eleicao.destroy

    respond_to do |format|
      format.html { redirect_to eleicaos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/eleicaos_helper.rb
module EleicaosHelper
end

app/views/eleicaos/_form.html.erb
<%= simple_form_for(@eleicao) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :ano %>
    <%= f.input :status, :label => "Ativa" %>
  </div>

  <div class="form-inputs">
    <%= f.button :submit, "Salvar" %>
  </div>
<% end %>

app/views/eleicaos/edit.html.erb
<div class="page-header"><h1> eleicao</h1></div>

<%= render 'form' %>

<%= link_to content_tag(:span, "Exibir"), @eleicao %> |
<%= link_to content_tag(:span, "Voltar"), eleicaos_path %>

app/views/eleicaos/index.html.erb
<div class="page-header"><h1>Eleicões</h1></div>

<table class="table table-condensed table-striped">
  <tr>
    <th>Ano</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @eleicaos.each do |eleicao| %>
  <tr>
    <td><%= eleicao.ano %></td>
    <td><%= eleicao.status ? "Em andamento" : "Fechada" %></td>
    <td><%= link_to content_tag(:span, "Exibir"), eleicao, :class => "btn btn-small" %></td>
    <td><%= link_to content_tag(:span, "Alterar"), edit_eleicao_path(eleicao), :class => "btn btn-small" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nova Eleicao', new_eleicao_path %>

app/views/eleicaos/new.html.erb
<div class="page-header"><h1>Nova eleicao</h1></div>

<%= render 'form' %>

app/views/eleicaos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Ano:</b>
  <%= @eleicao.ano %>
</p>

<p>
  <b>Status:</b>
  <%= @eleicao.status %>
</p>


<%= link_to content_tag(:span, "Alterar"), edit_eleicao_path(@eleicao) %> |
<%= link_to content_tag(:span, "Voltar"), eleicaos_path %>